import type { Metadata } from "next";
import { NowPlayingContextProvider } from "react-nowplaying";
import { ToastContextProvider } from "@/context/Toast";
import { MicrophoneContextProvider } from "@/context/Microphone";
import { AudioStoreContextProvider } from "@/context/AudioStore";
import { MessageMetadataContextProvider } from "@/context/MessageMetadata";
import { DeepgramContextProvider } from "@/context/Deepgram";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function Layout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <div style={{ height: "100vh" }}>
            <ToastContextProvider>
                <MicrophoneContextProvider>
                    <AudioStoreContextProvider>
                        <NowPlayingContextProvider>
                            <MessageMetadataContextProvider>
                                <DeepgramContextProvider>{children}</DeepgramContextProvider>
                            </MessageMetadataContextProvider>
                        </NowPlayingContextProvider>
                    </AudioStoreContextProvider>
                </MicrophoneContextProvider>
            </ToastContextProvider>
        </div>
    );
}
